# See http://travis-ci.org/encukou/gillcup

language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
install:
  - python setup.py develop
  - pip install pytest
  - pip install mako
script: py.test
